"""add PendingUser model

Revision ID: 02ba9e49428d
Revises: a953da8a43a5
Create Date: 2026-05-23 16:13:05.768225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ba9e49428d'
down_revision = 'a953da8a43a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('verification_code', sa.Integer(), nullable=False),
    sa.Column('code_expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_pending_user_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_pending_user_verification_code'), ['verification_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_user_verification_code'))
        batch_op.drop_index(batch_op.f('ix_pending_user_username'))
        batch_op.drop_index(batch_op.f('ix_pending_user_email'))

    op.drop_table('pending_user')
    # ### end Alembic commands ###
