"""add Track table

Revision ID: 533a9c41d9ac
Revises: 02ba9e49428d
Create Date: 2026-05-23 18:53:40.083620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533a9c41d9ac'
down_revision = '02ba9e49428d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('artist', sa.String(length=120), nullable=True),
    sa.Column('filename', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_artist'), ['artist'], unique=False)
        batch_op.create_index(batch_op.f('ix_track_filename'), ['filename'], unique=True)
        batch_op.create_index(batch_op.f('ix_track_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_track_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_user_id'))
        batch_op.drop_index(batch_op.f('ix_track_title'))
        batch_op.drop_index(batch_op.f('ix_track_filename'))
        batch_op.drop_index(batch_op.f('ix_track_artist'))

    op.drop_table('track')
    # ### end Alembic commands ###
